### ISSUE TITLE
get_tbv

### ISSUE THREAD

**Issue by mollypak** [cobeylab/HPV-model#1]
Hi,

 Line 31 in data_to_pomp_object.R will not run. The "make_model_Panel" function uses a function "get_tbv", which appears not to exist.

**Comment by slr72090** [comment]
Hello! 
The "get_tbv" function is in the "utility_functions.R" script. if you are running the "generate_pomp_object.R" script to make a panel pomp, it will source the "utility_functions.R" script, and therefore the function is loaded for the "data_to_pomp_object.R" script to use. If you would like to use "data_to_pomp_object.R" independently, you can load the functions from "utility_functions.R".  One other thing to note is that, since 2017,  POMP has changed the way that it handles covariate tables . Unless you are running this code with an early version of Pomp/panelPomp, you will likely need to update the formatting in keeping with the current pomp conventions (https://kingaa.github.io/pomp/index.html) when you are creating the panel objects
